config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do

  constraints(host: "app.officemomsanddads.com", format: "html") do
    get ":any", to: redirect(host: "app.fosterful.org", path: "/%{any}"), any: /.*/
  end

  constraints(host: "app-staging.officemomsanddads.com", format: "html") do
    get ":any", to: redirect(host: "app-staging.fosterful.org", path: "/%{any}"), any: /.*/
  end

  devise_for :users, controllers: {
    invitations: 'invitations'
  }, skip: [:registrations]

  ActiveAdmin.routes(self)
  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :needs do
    resources :shifts, except: %i[new]
    patch 'mark_unavailable', on: :member
    post 'office_social_workers', on: :collection
  end

  resources :shift_surveys, only: %i[edit update], param: :token

  get 'verify' => 'verifications#index', as: :verify
  post 'send_code' => 'verifications#send_code', as: :send_code
  post 'check_code' => 'verifications#check_code', as: :check_code

  get 'dashboard/reports' => 'dashboard#reports'
  get 'dashboard/download_report' => 'dashboard#download_report'
  get 'dashboard/users' => 'dashboard#users'
  get 'dashboard/query'

  root to: 'needs#index'
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  include DateRangeFilterHelper

  CHILDREN_BY_COUNTY     = 'total-children-served-by-county'
  CHILDREN_BY_DEMO       = 'total-children-by-demographic'
  CHILDREN_BY_OFFICE     = 'total-children-served-by-office'
  CHILDREN_BY_STATE      = 'total-children-served-by-state'
  HOURS_BY_COUNTY        = 'total-volunteer-hours-by-county'
  HOURS_BY_OFFICE        = 'total-volunteer-hours-by-office'
  HOURS_BY_STATE         = 'total-volunteer-hours-by-state'
  HOURS_BY_USER          = 'total-volunteer-hours-by-user'
  VOLUNTEERS_BY_LANGUAGE = 'total-volunteers-by-spoken-language'
  VOLUNTEERS_BY_RACE     = 'total-volunteers-by-race'
  # RESPONSES_BY_SHIFT     = 'survey-responses-by-shift'

  SAFE_MODELS = %w(Office User ShiftSurvey).freeze

  def users
    redirect_to :root unless coordinator_or_admin?

    @data =
      if current_user.admin?
        fetch_office_users_data(Office.all)
      else
        fetch_office_users_data(current_user.offices)
      end
  end

  def query
    redirect_to :root unless coordinator_or_admin?

    @office = Office.find(params[:office_id]) if params[:office_id].present?

    if params[:start_date].blank?
      params[:start_date] =
        Time.zone.now.beginning_of_month.to_date.to_s
    end

    @start_date = params[:start_date]

    params[:end_date] = Time.zone.now.end_of_month.to_date.to_s if params[:end_date].blank?

    @end_date = params[:end_date]

    needs_analysis_by_date_and_office
  end

  def reports
    redirect_to :root unless DashboardPolicy.new(current_user).reports?
  end

  def download_report
    redirect_to :root unless DashboardPolicy.new(current_user).reports?

    return redirect_to dashboard_download_report_path unless sensitive_params_are_safe

    set_download_report_variables

    respond_to do |format|
      format.csv do
        headers['Content-Disposition'] = content_disposition(params[:filename])
        headers['Content-Type']        = 'text/csv'
        dynamic_template_path = "dashboard/#{params[:data_method]}_template"
        if template_exists?(dynamic_template_path)
          render dynamic_template_path, format: :csv
        else
          render 'report_template', format: :csv
        end
      end
    end
  end

  private

  def set_download_report_variables
    @headers = params[:headers]
    @data =
      if params[:state]
        params[:model].constantize.send(
          params[:data_method], current_user, params[:state], params[:start_date],
          params[:end_date]
        )
      else
        params[:model].constantize.send(
          params[:data_method], current_user, params[:start_date], params[:end_date]
        )
      end
  end

  def fetch_office_users_data(offices)
    offices.each_with_object({}) do |office, hash|
      hash[office.name] = office.users
    end
  end

  def sensitive_params_are_safe
    params[:model].in?(SAFE_MODELS) &&
      params[:data_method].in?([
        CHILDREN_BY_COUNTY,
        CHILDREN_BY_DEMO,
        CHILDREN_BY_OFFICE,
        CHILDREN_BY_STATE,
        HOURS_BY_COUNTY,
        HOURS_BY_OFFICE,
        HOURS_BY_STATE,
        HOURS_BY_USER,
        VOLUNTEERS_BY_LANGUAGE,
        VOLUNTEERS_BY_RACE
      ].map(&:underscore))
  end

  def content_disposition(report_name)
    "attachment; filename=\"#{DateTime.current.to_i}-#{report_name}.csv\""
  end

  def coordinator_or_admin?
    DashboardPolicy.new(current_user).users?
  end

  def needs_analysis_by_date_and_office
    dashboard_queries = Services::DashboardQueries.new(
      params[:office_id],
      params[:start_date],
      params[:end_date]
    )

    @user_list_by_hours_volunteered = dashboard_queries.users_by_hours_volunteered
    @user_list_by_need_created = dashboard_queries.users_by_needs_created
    @hours_volunteered = dashboard_queries.hours_volunteered
    @needs_created_count = dashboard_queries.needs_created
    @shifts_created_count = dashboard_queries.shifts_created
    @shifts_claimed_count = dashboard_queries.shifts_claimed
    @shifts_unclaimed_count = dashboard_queries.shifts_unclaimed
  end
end

app/views/dashboard/_date_range_picker.html.haml
%p Choosing a date range will constrain reports to those dates:

= form_with method: 'GET' do |f|
  = f.text_field :start_date, value: "#{@start_date}",
    data: { controller: "flatpickr", flatpickr_alt_format: t("date.formats.long"), flatpickr_alt_input: true, flatpickr_allow_Input: true }
  = f.text_field :end_date, value: "#{@end_date}",
    data: { controller: "flatpickr", flatpickr_alt_format: t("date.formats.long"), flatpickr_alt_input: true, flatpickr_allow_Input: true }
  = f.submit "Submit"

app/views/dashboard/_form.html.haml
= form_with method: 'GET' do |f|
  -# what if there are no office?
  = f.select :office_id, current_user.offices.map { |office| [office.name, office.id] }
  %div
  = f.text_field :start_date, value: "#{@start_date}",
    data: { controller: "flatpickr", flatpickr_alt_format: t("date.formats.long"), flatpickr_alt_input: true, flatpickr_allow_Input: true }
  = f.text_field :end_date, value: "#{@end_date}",
    data: { controller: "flatpickr", flatpickr_alt_format: t("date.formats.long"), flatpickr_alt_input: true, flatpickr_allow_Input: true }
  = f.submit "Submit"

app/views/dashboard/dashboard.html.haml
%h1 Data Breakdown
%p Select Which Office:
=render "form"
%br/
%h3= "#{@office} during #{@start_date} - #{@end_date}"

%h3 Most active by # of hours
%table
  %thead
    %tr
      %th ID
      %th Role
      %th Name
      %th Email
      %th Hours Volunteered
  %tbody
    - @users_active_by_shift_claimed.each do |user|
      %tr
        %td= user[:id]
        %td= user[:role]
        %td= user[:name]
        %td= user[:email]
        %td= user[:hours]

%h3 Most active by # of needs created
%table
  %thead
    %tr
      %th ID
      %th Role
      %th Name
      %th Email
      %th Needs Created
  %tbody
    - @users_active_by_need_created.each do |user|
      %tr
        %td= user[:id]
        %td= user[:role]
        %td= user[:name]
        %td= user[:email]
        %td= user[:needs_created]

%h3 Shifts
%table
  %thead
    %tr
      %th Needs Created
      %th Shifts Created
      %th Filled Shifts
      %th Unfilled Shifts
  %tbody
    %tr
      %td= @total_needs_created
      %td= @total_shifts_created
      %td= @total_shifts_claimed
      %td= @total_shifts_unclaimed

app/views/dashboard/query.haml
%h1 Data Breakdown
%p Select Which Office:
=render "form"

- if @office
  .grid-x.margin-vertical-1
  .cell
    %h2= "#{@office}"

    .grid-x.grid-padding-left{ data: { controller: "dashboard-query" } }
      .cell.large-12{ data: { target: "dashboard-query.hideableHours" }, hidden: true}
        .card
          .card-section
            .grid-x.grid-margin-x
              .cell.auto
                %h3 Most active by number of hours volunteered
              .cell.shrink
                .button{ data: { action: "click->dashboard-query#hideHoursTargets" } } Close

            %table{class: 'hover'}
              %thead
                %tr
                  %th Role
                  %th Name
                  %th Email
                  %th Hours Volunteered
              %tbody
                - @user_list_by_hours_volunteered .each do |user|
                  %tr
                    %td= user[:role]
                    %td= user[:name]
                    %td= user[:email]
                    %td= user[:hours]
                %tr
                  %td
                  %td
                  %td
                    %strong Total Hours
                  %td
                    %strong= @hours_volunteered

      .cell.large-12{ data: { target: "dashboard-query.hideableNeeds" }, hidden: true}
        .card
          .card-section
            .grid-x.grid-margin-x
              .cell.auto
                %h3 Most active by number of needs created
              .cell.shrink
                .button{ data: { action: "click->dashboard-query#hideNeedsTargets" } } Close

            %table{class: 'hover'}
              %thead
                %tr
                  %th Role
                  %th Name
                  %th Email
                  %th Needs Created
              %tbody
                - @user_list_by_need_created.each do |user|
                  %tr
                    %td= user[:role]
                    %td= user[:name]
                    %td= user[:email]
                    %td= user[:needs_created]
                %tr
                  %td
                  %td
                  %td
                    %strong Total Needs
                  %td
                    %strong= @needs_created_count

      .cell.small-4
        .card
          .card-section
            %h2
              %strong Needs Created
            .grid-x.grid-margin-x
              .cell.auto
                %h2
                  %strong= @needs_created_count
              .cell.shrink
                .button{ data: { action: "click->dashboard-query#toggleNeedsTargets" } } Expand

      .cell.small-4
        .card
          .card-section
            %h2
              %strong Hours Volunteered
            .grid-x.grid-margin-x
              .cell.auto
                %h2
                  %strong= @hours_volunteered
              .cell.shrink
                .button{ data: { action: "click->dashboard-query#toggleHoursTargets" } } Expand

      .cell.small-4
        .card
          .card-section
            %h2
              %strong Shifts Created
            %h2
              %strong= @shifts_created_count
      .cell.small-4.small-offset-2
        .card
          .card-section
            %h2
              %strong Shifts Claimed
            %h2
              %strong= @shifts_claimed_count
      .cell.small-4
        .card
          .card-section
            %h2
              %strong Shifts Unclaimed
            %h2
              %strong= @shifts_unclaimed_count

- else
  %h3 Please submit your form after selecting your office.

app/views/dashboard/report_template.csv.haml
= CSV.generate_line @headers
- @data.each do |cell1, cell2|
  = CSV.generate_line([cell1.is_a?(Array) ? cell1.to_csv(row_sep: nil) : cell1, cell2]).html_safe

app/views/dashboard/reports.html.haml
-# = react_component("DashboardReportsDateRangePicker/index")
=render "date_range_picker"

.grid-x.margin-vertical-1
  .cell.small-6
    %h2 By Office

    .grid-x.grid-padding-left
      .cell.large-6
        .card
          .card-section
            %h5
              %strong Volunteer Hours
            %p This report contains the number of hours served at the child welfare office by volunteers per child welfare office.
            .flex-container.flex-dir-row-reverse
              = link_to dashboard_download_report_url(headers: ['Office Name', 'Volunteer Hours'], data_method: DashboardController::HOURS_BY_OFFICE.underscore, filename: DashboardController::HOURS_BY_OFFICE, model: 'Office', format: :csv), target: '_blank', class: 'button get_report' do
                %i.fas.fa-file-download{style: 'margin-right: 3px;' }
                Download
      .cell.large-6
        .card
          .card-section
            %h5
              %strong Children Served
            %p This report contains the number of children served at the child welfare office by volunteers per child welfare office.
            .flex-container.flex-dir-row-reverse
              = link_to dashboard_download_report_url(headers: ['Office Name', 'Children Served'], data_method: DashboardController::CHILDREN_BY_OFFICE.underscore, filename: DashboardController::CHILDREN_BY_OFFICE, model: 'Office', format: :csv), target: '_blank', class: 'button get_report' do
                %i.fas.fa-file-download{style: 'margin-right: 3px;' }
                Download

  .cell.small-6
    %h2 By State

    .grid-x.grid-padding-left
      .cell.large-6
        .card
          .card-section
            %h5
              %strong Volunteer Hours
            %p This report contains the number of hours served at the child welfare office by volunteers per state.
            .flex-container.flex-dir-row-reverse
              = link_to dashboard_download_report_url(headers: ['State', 'Volunteer Hours'], data_method: DashboardController::HOURS_BY_STATE.underscore, filename: DashboardController::HOURS_BY_STATE, model: 'Office', format: :csv), target: '_blank', class: 'button get_report' do
                %i.fas.fa-file-download{style: 'margin-right: 3px;' }
                Download
      .cell.large-6
        .card
          .card-section
            %h5
              %strong Children Served
            %p This report contains the number of children served at the child welfare office by volunteers per state.
            .flex-container.flex-dir-row-reverse
              = link_to dashboard_download_report_url(headers: ['State', 'Children Served'], data_method: DashboardController::CHILDREN_BY_STATE.underscore, filename: DashboardController::CHILDREN_BY_STATE, model: 'Office', format: :csv), target: '_blank', class: 'button get_report' do
                %i.fas.fa-file-download{style: 'margin-right: 3px;' }
                Download

.grid-x.margin-bottom-1
  .cell
    %h2 By County

    .grid-x.grid-padding-left
      .cell.small-6
        .card
          .card-section
            %h5
              %strong Volunteer Hours
            %p This report contains the number of hours served at the child welfare office by volunteers per county.

            = label_tag(:state)
            = select_tag :state, options_for_select(Address.distinct.pluck(:state))

            .flex-container.flex-dir-row-reverse
              = link_to dashboard_download_report_url(headers: ['County', 'Volunteer Hours'], data_method: DashboardController::HOURS_BY_COUNTY.underscore, filename: DashboardController::HOURS_BY_COUNTY, model: 'Office', format: :csv), target: '_blank', class: 'button  get_report_with_state' do
                %i.fas.fa-file-download{style: 'margin-right: 3px;' }
                Download

      .cell.small-6
        .card
          .card-section
            %h5
              %strong Children Served
            %p This report contains the number of children served at the child welfare office by volunteers per county.

            = label_tag(:state, 'State')
            = select_tag :state, options_for_select(Address.distinct.pluck(:state))

            .flex-container.flex-dir-row-reverse
              = link_to dashboard_download_report_url(headers: ['County', 'Children Served'], data_method: DashboardController::CHILDREN_BY_COUNTY.underscore, filename: DashboardController::CHILDREN_BY_COUNTY, model: 'Office', format: :csv), target: '_blank', class: 'button get_report_with_state' do
                %i.fas.fa-file-download{style: 'margin-right: 3px;' }
                Download

.grid-x
  .cell.small-9
    %h2 By Demographic

    .grid-x.grid-padding-left
      .cell.large-4
        .card
          .card-section
            %h5
              %strong Children by Demographic
            %p This report contains demographic information as indicated on the Scheduler intake form.
            .flex-container.flex-dir-row-reverse
              = link_to dashboard_download_report_url(headers: ['Preferred Language', 'Number of Children'], data_method: DashboardController::CHILDREN_BY_DEMO.underscore, filename: DashboardController::CHILDREN_BY_DEMO, model: 'Office', format: :csv), target: '_blank', class: 'button get_report' do
                %i.fas.fa-file-download{style: 'margin-right: 3px;' }
                Download

      .cell.large-4
        .card
          .card-section
            %h5
              %strong Volunteers Grouped By Race
            %p This report contains race/cultural information as self-reported by OMD volunteers.
            .flex-container.flex-dir-row-reverse
              = link_to dashboard_download_report_url(headers: ['Race', 'Number of Volunteers'], data_method: DashboardController::VOLUNTEERS_BY_RACE.underscore, filename: DashboardController::VOLUNTEERS_BY_RACE, model: 'Office', format: :csv), target: '_blank', class: 'button get_report' do
                %i.fas.fa-file-download{style: 'margin-right: 3px;' }
                Download

      .cell.large-4
        .card
          .card-section
            %h5
              %strong Volunteers Grouped By Spoken Language
            %p This report contains spoken language information as self-reported by OMD volunteers.
            .flex-container.flex-dir-row-reverse
              = link_to dashboard_download_report_url(headers: ['Language', 'Total Volunteer Hours'], data_method: DashboardController::VOLUNTEERS_BY_LANGUAGE.underscore, filename: DashboardController::VOLUNTEERS_BY_LANGUAGE, model: 'User', format: :csv), target: '_blank', class: 'button get_report' do
                %i.fas.fa-file-download{style: 'margin-right: 3px;' }
                Download

  .cell.medium-3
    %h2 By User

    .grid-x.grid-padding-left
      .cell
        .card
          .card-section
            %h5
              %strong Volunteer Hours
            %p This report contains volunteer hours served per OMD Volunteer.
            %br
            %br
            .flex-container.flex-dir-row-reverse
              = link_to dashboard_download_report_url(headers: ['id', 'First Name', 'Last Name', 'Total Volunteer Hours'], data_method: DashboardController::HOURS_BY_USER.underscore, filename: DashboardController::HOURS_BY_USER, model: 'User', format: :csv), target: '_blank', class: 'button get_report' do
                %i.fas.fa-file-download{style: 'margin-right: 3px;' }
                Download

                .grid-x.margin-bottom-1
  -# .cell
  -#   %h2 Shift Survey

  -#   .grid-x.grid-padding-left
  -#     .cell.small-6
  -#       .card
  -#         .card-section
  -#           %h5
  -#             %strong Shift Survey Responses
  -#           %p This report contains all volunteer responses to the end-of-shift surveys.
  -#           .flex-container.flex-dir-row-reverse
  -#             = link_to dashboard_download_report_url(data_method: DashboardController::RESPONSES_BY_SHIFT.underscore, filename: DashboardController::RESPONSES_BY_SHIFT, model: 'ShiftSurvey', format: :csv), target: '_blank', class: 'button get_report' do
  -#               %i.fas.fa-file-download{style: 'margin-right: 3px;' }
  -#               Download

app/views/dashboard/survey_responses_by_shift_template.csv.haml
= CSV.generate_line ShiftSurvey.attribute_names
- @data.each do |survey|
  = CSV.generate_line(survey.attributes.values).html_safe

app/views/dashboard/total_volunteer_hours_by_user_template.csv.haml
= CSV.generate_line @headers
- @data.each do |cell1, cell2|
  = CSV.generate_line([cell1, cell2].flatten).html_safe

app/views/dashboard/users.html.haml
= form_tag(dashboard_users_path, method: :get) do
  Name
  \#{text_field_tag :name}
  Email
  \#{text_field_tag :email}
  Role
  \#{text_field_tag :role}
  Role
  \#{text_field_tag :accepted?}

  \#{submit_tag 'Search', class: "btn btn-info"}

- @data.each do |office_name, users|
  %h2= office_name

  %table
    %thead
      %tr
        %th Name
        %th Email
        %th Role
        %th Invitation Status
    %tbody
      - users.each do |user|
        %tr
          %td= user
          %td= user.email
          %td= user.role_display
          %td= user.invitation_accepted_at ? 'Accepted' : 'Not yet accepted'

app/views/dashboard/volunteer_dashboard.html.haml
%h1 Volunteer statistics for #{@current_user.name}
-# = react_component("DashboardReportsDateRangePicker/index")

- if current_user.served_needs.any?
  - served_needs = current_user.served_needs.where("needs.start_at < ?", Time.zone.now).order('start_at')
  %p
    %strong First Need Served:
    %span= served_needs.first.start_at.strftime("%m/%d/%Y")
  %p
    %strong Last Need Served:
    %span= served_needs.last.start_at.strftime("%m/%d/%Y")
  %p
    %strong Total Hours Volunteered:
    %span= User.total_volunteer_hours_by_user(@current_user, nil, nil).values.first.to_i
  %p
    %strong Total Children Served:
    %span= User.total_children_by_user(@current_user, nil, nil)
- else
  %p
    Complete at least one shift to see statistics here.