config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do

  constraints(host: "app.officemomsanddads.com", format: "html") do
    get ":any", to: redirect(host: "app.fosterful.org", path: "/%{any}"), any: /.*/
  end

  constraints(host: "app-staging.officemomsanddads.com", format: "html") do
    get ":any", to: redirect(host: "app-staging.fosterful.org", path: "/%{any}"), any: /.*/
  end

  devise_for :users, controllers: {
    invitations: 'invitations'
  }, skip: [:registrations]

  ActiveAdmin.routes(self)
  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :needs do
    resources :shifts, except: %i[new]
    patch 'mark_unavailable', on: :member
    post 'office_social_workers', on: :collection
  end

  resources :shift_surveys, only: %i[edit update], param: :token

  get 'verify' => 'verifications#index', as: :verify
  post 'send_code' => 'verifications#send_code', as: :send_code
  post 'check_code' => 'verifications#check_code', as: :check_code

  get 'dashboard/reports' => 'dashboard#reports'
  get 'dashboard/download_report' => 'dashboard#download_report'
  get 'dashboard/users' => 'dashboard#users'
  get 'dashboard/query'

  root to: 'needs#index'
end

app/models/need.rb
# frozen_string_literal: true

class Need < ApplicationRecord
  include NotificationConcern

  belongs_to :office
  belongs_to :user
  belongs_to :race, optional: true
  belongs_to :preferred_language,
             class_name: 'Language'
  has_and_belongs_to_many :age_ranges
  has_and_belongs_to_many :social_workers,
                          class_name:              'User',
                          join_table:              'needs_social_workers',
                          association_foreign_key: 'social_worker_id'
  has_many :shifts, dependent: :destroy
  has_many :users, through: :shifts
  has_many :shift_surveys
  has_many :children, dependent: :destroy

  accepts_nested_attributes_for :children, allow_destroy: true

  validates :start_at,
            :expected_duration,
            presence: true
  validates :expected_duration,
            numericality: { greater_than_or_equal_to: 60,
                            message:                  'must be at least one hour' }

  validate :intentional_start_at
  validate :at_least_one_child

  scope :current, lambda {
    where('start_at > ?', Time.zone.now.at_beginning_of_day)
      .order(start_at: :asc)
  }
  scope :on_date, lambda { |date|
    where('start_at between ? and ?', date.beginning_of_day, date.end_of_day)
      .order(start_at: :asc)
  }
  scope :has_claimed_shifts, lambda {
    where('EXISTS(SELECT 1 FROM shifts WHERE shifts.need_id = needs.id ' \
          'AND shifts.user_id IS NOT NULL)')
  }

  def self.total_children_served
    has_claimed_shifts.joins(:children).count('children.id')
  end

  alias_attribute :duration, :expected_duration

  def number_of_children
    children.count
  end

  def end_at
    start_at.advance(minutes: expected_duration)
  end

  def expired?
    end_at <= Time.zone.now
  end

  def effective_start_at
    [start_at, *shifts.pluck(:start_at)].min
  end

  def notification_candidates
    office
      .notifiable_users
      .where.not(id: unavailable_user_ids | [user_id])
  end

  def users_to_notify
    notification_candidates
      .then { |users| preferred_language_override.present? ? users : scope_users_by_language(users) }
      .then { |users| scope_users_by_age_ranges(users) }
      .then { |users| users.to_a | [user] }
  end

  def unavailable_users
    User.find(unavailable_user_ids)
  end

  def users_pending_response
    User.notifiable.where(id: notified_user_ids - unavailable_user_ids - shifts.pluck(:user_id))
  end

  def users_language_pending_response
    users_pending_response.where(first_language_id: preferred_language_id)
    .or(users_pending_response.where(second_language_id: preferred_language_id))
  end

  private

  # Midnight is the default selection, however is very unlikely to be intentionally selected.
  # Thus, regard it as equal to the start time not being present.
  # This forces the user to select an appropriate time.
  def intentional_start_at
    return if start_at.blank?

    errors.add(:start_at, 'must not be midnight') if start_at == start_at.midnight
  end

  def at_least_one_child
    return if children.any?

    errors.add(:base, 'At least one child is required')
  end
end

app/controllers/needs_controller.rb
# frozen_string_literal: true

class NeedsController < ApplicationController
  before_action :check_need_creation_disabled?, only: %i(new create edit update)

  def index
    authorize Need

    @needs = policy_scope(Need).includes(:shifts).order(:start_at)

    if current_user.scheduler? && params[:date]
      @date = Date.parse(params[:date])
      @needs = @needs.on_date(@date)
    else
      @date = nil
      @needs = @needs.current
    end
  end

  def show
    @need   = policy_scope(Need).includes(:shifts).find(params[:id])
    @shifts = @need.shifts.order(:start_at)

    authorize @need
  rescue ActiveRecord::RecordNotFound
    redirect_to(root_path, alert: "Sorry, we couldn't find that need.")
  end

  def new
    @need = Need.new

    authorize @need
  end

  def edit
    @need = policy_scope(Need).find(params[:id])

    authorize @need
  end

  def create
    convert_to_minutes!
    @need = current_user.needs.build(permitted_attributes(Need))

    authorize @need

    if @need.valid? && @need.update(shifts: Services::BuildNeedShifts.call(@need))
      Services::Notifications::Needs.new(@need, :create).notify

      redirect_to(@need)
    else
      render(:new)
    end
  end

  def update
    @need = policy_scope(Need).find(params[:id])
    @need.assign_attributes(permitted_attributes(@need))

    authorize @need

    if @need.save
      redirect_to(@need)
    else
      render(:edit)
    end
  end

  def destroy
    @need = policy_scope(Need).find(params[:id])

    authorize @need

    if @need.destroy
      Services::Notifications::Needs.new(@need, :destroy).notify

      redirect_to needs_path, flash: { success: 'Need successfully deleted' }
    else
      redirect_back fallback_location: needs_path,
                    flash:             { error: 'Failed to delete Need' }
    end
  end

  def mark_unavailable
    @need = policy_scope(Need).find(params[:id])
    authorize @need
    @need.unavailable_user_ids << current_user.id
    @need.save
    redirect_to @need
  end

  def office_social_workers
    office = policy_scope(Office).where(id: params[:office_id]).first
    render layout: false, locals: { office: office }
  end

  private

  def check_need_creation_disabled?
    return false unless need_creation_disabled?

    flash[:error] = redis.get('need_creation_disabled_msg').presence || 'Need creation disabled'
    redirect_to root_path
  end

  def convert_to_minutes!
    return unless params[:need] && params[:need][:expected_duration].present?

    params[:need][:expected_duration] = (params[:need][:expected_duration].to_f * 60).to_s
  end
end

app/helpers/needs_helper.rb
# frozen_string_literal: true

module NeedsHelper
  def race_options_for_select
    Race.pluck(:name, :id)
  end

  def language_options_for_select
    language_options = Language.all.map { |l| [l.name, l.id] }
    english = language_options.find { |l| l[0] == 'English' }
    options_for_select(language_options, selected: english[1])
  end
end

app/views/needs/_form_fields.html.haml
- if f.object.errors.any?
  #error_explanation
    %h5
      = pluralize(f.object.errors.count, "error")
      prohibited this task from being saved:
    %ul
      - f.object.errors.full_messages.each do |msg|
        %li= msg

%fieldset.fieldset
  %legend Start Date/Time
  .grid-x
    .cell
      = react_component("NewNeedDatePicker/index", { startAt: f.object.start_at, exists: f.object.id.present? })
%fieldset.fieldset
  %legend Expected Duration
  .grid-x.grid-margin-x
    .cell.small-12.medium-shrink
      = f.label :expected_duration, class: 'duration-label' do
        = f.number_field :expected_duration, min: 1, max: 9, step: 0.25, class: 'duration-input', disabled: action == :edit
        .align-self-middle{style: 'padding-left:.5rem;'}
          %p Hours
    .cell.small-12.medium-auto
      .slider{ data: { slider: true, step: '0.25', start: '1', end: '9', initial_start: @need.expected_duration.to_f / 60 }, class: (action == :edit ? 'disabled' : '') }
        %span.slider-handle{ role: 'slider', data: { slider_handle: true}, tabindex: '1', aria: { controls: 'need_expected_duration' } }
        %span.slider-fill{ data: { slider_fill: true } }
%fieldset.fieldset
  %legend Office
  .grid-x
    .cell
      = f.label :office_id do
        = f.select :office_id, options_for_select(policy_scope(Office).map { |o| [o.name, o.id]}), { include_blank: false }, disabled: action == :edit, data: { action: 'change->new-need-form#handleOfficeChange' }
%fieldset.fieldset
  %legend Child Welfare Workers
  .grid-x
    .cell
      = f.label :social_worker_ids do
        %div{ data: { target: 'new-need-form.socialWorkerSelectContainer' } }
          = render template: 'needs/office_social_workers', locals: { office: @need.office || policy_scope(Office).first }
.grid-x
  .cell
    = react_component("NeedChildForm/index", { children: @need.children, childSexes: Child.sexes.keys }, id: 'NeedChildForm')
%fieldset.fieldset
  %legend Preferred Culture
  .grid-x
    .cell
      = f.label :race_id do
        = f.select :race_id, options_for_select(race_options_for_select), { include_blank: true }, class: 'single'
%fieldset.fieldset
  %legend Preferred Language
  .grid-x
    .cell
      = f.label :preferred_language_id do
        = f.select :preferred_language_id, language_options_for_select, { include_blank: false }, class: 'single'
%fieldset.fieldset
  %legend Notes
  .grid-x
    .cell
      = f.label :notes do
        = f.text_area :notes, :rows => 6, :placeholder => 'Enter notes here'

app/views/needs/edit.html.haml
- content_for :page_header do
  .header-text Update a Need
= form_for(@need, url: {action: 'update'}, html: { method: :put }) do |f|
  = render partial: 'form_fields', locals: { f: f, action: :edit }
  .grid-x
    .cell
      .actions
        = f.submit "Update", class: 'button'

app/views/needs/index.html.haml
- content_for :page_header do
  .header-text Fosterful Scheduler

.grid-x
  .cell
    - if current_user.scheduler?
      .float-right
        = react_component("NeedsIndexDatePicker/index", { date: @date })
    %h5.separator-left Needs
    %table.responsive-card-table.hover.unstriped
      %thead
        %tr
          %th Office
          %th # of Children
          %th Start At
          %th Shifts
      %tbody
        - @needs.each do |need|
          %tr
            %td{data: {label: 'Office'}}= link_to need.office, need_path(need)
            %td{data: {label: 'Children'}}= link_to need.number_of_children, need_path(need)
            %td{data: {label: 'Start At'}}= link_to need.effective_start_at.strftime('%l:%M%P %A, %b %d'), need_path(need)
            %td{data: {label: 'Shifts'}}= link_to need.shifts.count, need_path(need)

app/views/needs/new.html.haml
- content_for :page_header do
  .header-text Create a Need
= form_for(@need, url: {action: 'create'}, html: { method: :post, data: { controller: 'new-need-form' } }) do |f|
  = render partial: 'form_fields', locals: { f: f, action: :new }
  .grid-x
    .cell
      .actions
        = f.submit "Create", class: 'button'

app/views/needs/office_social_workers.html.haml
- if office.present? && office.users.social_workers.any?
  - selected = @need.present? ? @need.social_worker_ids : nil
  = hidden_field_tag "need[social_worker_ids][]", ""
  = select_tag "need[social_worker_ids]", options_from_collection_for_select(office.users.social_workers, :id, :name, selected), { include_blank: false, multiple: true, class: "multiple" }
- else
  = select_tag "need[social_worker_ids]", [], disabled: true

app/views/needs/show.html.haml
- content_for :page_header do
  .header-text Need at #{@need.effective_start_at.strftime('%l:%M%P on %A, %b %d')}
- if policy(@need).edit? && !@need.expired?
  - content_for :nav_buttons do
    = link_to 'Manage Shifts', need_shifts_path(@need), class: 'button primary'
    = link_to 'Edit Need', edit_need_path(@need), class: 'button secondary'
    = link_to 'Delete Need', need_path(@need), method: :delete, class: 'button alert', data: { confirm: 'Are you sure you want to destroy this Need?' }
%h2 Details
%table.unstriped.need-details
  %tbody
    %tr
      %td Start Time
      %td
        %strong= @need.effective_start_at.strftime('%l:%M%P')
        %br
        = @need.start_at.strftime('%A, %b %d')
    %tr
      %td Office
      %td
        %strong= @need.office
    %tr
      %td Child Welfare Workers
      %td
        %ul.social_workers
          - @need.social_workers.each do |social_worker|
            %li
              %strong= social_worker.name
              - if social_worker.phone.present?
                = "(Phone: #{social_worker.phone})"
    %tr
      %td Requested By
      %td
        %strong= @need.user.name
    %tr
      %td Number of Children
      %td
        %strong= @need.children.count
    %tr
      %td Preferred Language
      %td
        %strong= @need.preferred_language.name
    %tr
      %td Ignore Preferred Language for Notifications
      %td
        %strong= @need.preferred_language_override.to_s.capitalize
    - if @need.notes.present?
      %tr
        %td Notes
        %td
          %strong= simple_format("#{@need.notes}")
.grid-x
  .cell
    - @need.children.each_with_index do |child, index|
      .card{style: "margin-bottom: 3rem;"}
        .card-divider
          %h5{style: "font-weight: bold;"} Child #{index + 1}
        .card-section{style: "padding:0;"}
          %table.unstriped.need-details{style: "border: none;"}
            %tbody{style: "border: none;"}
              %tr
                %td Age
                %td
                  %strong= child.age
              %tr
                %td Gender
                %td
                  %strong= child.sex.dasherize.capitalize
              - if child.notes.present?
                %tr
                  %td Notes
                  %td
                    %strong= child.notes
%h2 Shifts
.shifts-container
  - @shifts.each do |shift|
    %hr
    .grid-x.grid-margin-y.grid-margin-x.align-spaced.align-middle
      .cell.small-12.medium-9.large-10.shift{ class: shift.user_id ? 'secondary claimed' : 'success unclaimed' }
        .grid-x.grid-padding-x.grid-padding-y
          .cell.text-center
            %strong= shift.start_at.strftime('%I:%M%p')
            - if policy(@need).edit?
              = " - #{shift.user&.to_s}"
      .cell.small-12.medium-3.large-2
        - if !shift.expired? && shift.user_id == current_user.id
          = link_to need_shift_path(@need, shift, shift: { user_id: nil }), method: :put, class: 'button alert expanded' do
            .grid-x.hide-for-small-only.align-middle
              .cell.small-6.small-text-right.medium-3
                %i.fas.fa-calendar-minus
              .cell.small-6.medium-9.text-left
                Release Shift
            .grid-x.show-for-small-only
              .cell
                %i.fas.fa-calendar-minus
                Release Shift
        - if !shift.expired? && shift.user_id == nil
          = link_to need_shift_path(@need, shift, shift: { user_id: current_user.id }), method: :put, class: 'button success expanded' do
            .grid-x.hide-for-small-only.align-middle
              .cell.small-6.small-text-right.medium-3
                %i.fas.fa-calendar-plus
              .cell.small-6.small-text-left.medium-9.text-left
                Claim Shift
            .grid-x.show-for-small-only
              .cell
                %i.fas.fa-calendar-plus
                Claim Shift
- if @need.notified_user_ids.present?
  - if @need.notified_user_ids.include?(current_user.id)
    %br
    .unavailable-container
      - if @need.shifts.where(user_id: current_user.id).present?
        %p You have claimed a shift.
      - elsif @need.unavailable_user_ids.include?(current_user.id)
        %p You have marked yourself as unavailable for this request.
      - else
        = form_tag mark_unavailable_need_path(@need), method: :patch do
          = submit_tag 'I am not available for this request.', class: 'button alert'
        %br
  - if policy(@need).view_responses?
    .responses-container{data: { controller: 'needs-show' }}
      %p
        = link_to pluralize(@need.unavailable_users.size, 'volunteer'), '#', id: 'toggle-unavailable-list', data: { action: 'needs-show#toggleUserListDisplay', list_id: '#unavailable-list' }
        cannot fill this request
      %ul#unavailable-list.hide
        - @need.unavailable_users.each do |user|
          %li= user.name
      %p
        = link_to pluralize(@need.users_pending_response.size, 'volunteer'), '#', id: 'toggle-pending-list', data: { action: 'needs-show#toggleUserListDisplay', list_id: '#pending-list' }
        = "have not yet responded"
      %ul#pending-list.hide
        - @need.users_pending_response.each do |user|
          %li= user.name
      %p
        = link_to pluralize(@need.users_language_pending_response.size, 'volunteer'), '#', id: 'toggle-language-list', data: { action: 'needs-show#toggleUserListDisplay', list_id: '#language-list' }
        who speaks the preferred language has not responded
      %ul#language-list.hide
        - @need.users_language_pending_response.each do |user|
          %li= user.name