config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do

  constraints(host: "app.officemomsanddads.com", format: "html") do
    get ":any", to: redirect(host: "app.fosterful.org", path: "/%{any}"), any: /.*/
  end

  constraints(host: "app-staging.officemomsanddads.com", format: "html") do
    get ":any", to: redirect(host: "app-staging.fosterful.org", path: "/%{any}"), any: /.*/
  end

  devise_for :users, controllers: {
    invitations: 'invitations'
  }, skip: [:registrations]

  ActiveAdmin.routes(self)
  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :needs do
    resources :shifts, except: %i[new]
    patch 'mark_unavailable', on: :member
    post 'office_social_workers', on: :collection
  end

  resources :shift_surveys, only: %i[edit update], param: :token

  get 'verify' => 'verifications#index', as: :verify
  post 'send_code' => 'verifications#send_code', as: :send_code
  post 'check_code' => 'verifications#check_code', as: :check_code

  get 'dashboard/reports' => 'dashboard#reports'
  get 'dashboard/download_report' => 'dashboard#download_report'
  get 'dashboard/users' => 'dashboard#users'
  get 'dashboard/query'

  root to: 'needs#index'
end

app/controllers/verifications_controller.rb
# frozen_string_literal: true

class VerificationsController < ApplicationController
  skip_before_action :enforce_verification

  VERIFY_SID = Rails.application.credentials.dig(:twilio, :verify_sid)

  def index; end

  def send_code
    $twilio.verify.services(VERIFY_SID).verifications
      .create(to: current_user.e164_phone, channel: 'sms')
    redirect_to verify_path(verification_sent: true)
  end

  def check_code
    code = params[:code]
    check = $twilio.verify.services(VERIFY_SID).verification_checks
      .create(to: current_user.e164_phone, code: code)
    if check.status == 'approved'
      current_user.update(verified: true)
      flash[:notice] = 'Phone number has been verified!'
      redirect_to root_path
    else
      flash[:notice] = 'Verification failed'
      redirect_to verify_path
    end
  end
end

app/views/verifications/index.html.haml
.grid-x.grid-margin-x.align-middle.margin-top-3
  .cell.auto
  .cell.small-12.medium-9.large-6
    .card
      .card-divider
        Phone verification
      .card-section
        - if current_user.verified?
          %p
            = "Your phone number (#{current_user.phone}) has already been verified."
            %br
            = link_to "Change my phone number", edit_user_registration_path 
        - else
          - if params[:verification_sent]
            .callout.primary
              %p Please submit the verification code you received via text message at #{current_user.phone}.
            = form_tag(check_code_path) do
              .grid-container
                .grid-x.grid-padding-x
                  .medium-4.cell
                    = text_field_tag :code, nil, placeholder: 'Verification code'
                  .cell.auto
                    = submit_tag "Submit", class: 'primary button'
              %small
                Didn't receive a verification code?
                = link_to 'Click here to try again.', verify_path
          - else
            .callout.warning
              %p Please verify your phone number. Get started by clicking the 'Send verification code' button below. When you receive the verification code at #{current_user.phone}, submit it on the next screen.
            %p
              = "Your phone number: #{current_user.phone}"
              %br
              = link_to "Change my phone number", edit_user_registration_path
            = link_to 'Send verification code', send_code_path, class: 'primary button', method: :post
            .margin-top-1
              %small
                Already have a verification code?
                = link_to 'Click here to enter it now.', verify_path(verification_sent: true)

  .cell.auto