config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do

  constraints(host: "app.officemomsanddads.com", format: "html") do
    get ":any", to: redirect(host: "app.fosterful.org", path: "/%{any}"), any: /.*/
  end

  constraints(host: "app-staging.officemomsanddads.com", format: "html") do
    get ":any", to: redirect(host: "app-staging.fosterful.org", path: "/%{any}"), any: /.*/
  end

  devise_for :users, controllers: {
    invitations: 'invitations'
  }, skip: [:registrations]

  ActiveAdmin.routes(self)
  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :needs do
    resources :shifts, except: %i[new]
    patch 'mark_unavailable', on: :member
    post 'office_social_workers', on: :collection
  end

  resources :shift_surveys, only: %i[edit update], param: :token

  get 'verify' => 'verifications#index', as: :verify
  post 'send_code' => 'verifications#send_code', as: :send_code
  post 'check_code' => 'verifications#check_code', as: :check_code

  get 'dashboard/reports' => 'dashboard#reports'
  get 'dashboard/download_report' => 'dashboard#download_report'
  get 'dashboard/users' => 'dashboard#users'
  get 'dashboard/query'

  root to: 'needs#index'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit

  DEFAULT_ERROR = 'Whoops! Something went wrong.'

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :enforce_verification, if: :user_signed_in?
  around_action :set_time_zone, if: :user_signed_in?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def authenticate_admin
    return if current_user.admin?

    redirect_to root_path, flash: { error: 'Not authorized.' }
  end

  def redis
    @redis ||= begin
      redis_connection = Redis.new(
        url: Rails.application.credentials.redis_url || ENV.fetch('REDIS_URL',
                                                                  nil), ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }
      )
      Redis::Namespace.new(Rails.env, redis: redis_connection)
    end
  end
  helper_method :redis

  def need_creation_disabled?
    redis.get('need_creation_disabled').present?
  end
  helper_method :need_creation_disabled?

  private

  def configure_permitted_parameters
    policy = Pundit.policy(current_user || User.new, User)
    devise_parameter_sanitizer
      .permit(:account_update,
              keys: policy.permitted_attributes_for_account_update)
    devise_parameter_sanitizer
      .permit(:invite, keys: policy.permitted_attributes_for_create)
    devise_parameter_sanitizer
      .permit(:accept_invitation, keys: policy.permitted_attributes)
  end

  def user_not_authorized
    respond_to do |format|
      format.html do
        flash[:alert] = 'You are not authorized to perform this action.'

        redirect_to(request.referer || root_path)
      end
      format.json do
        render json: {}, status: :unauthorized
      end
    end
  end

  def set_time_zone
    Time.zone = current_user.time_zone
    yield
  ensure
    Time.zone = Scheduler::Application.config.time_zone
  end

  def enforce_verification
    return if current_user.verified? || devise_controller?

    redirect_to verify_path
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_classes
    { notice: 'success',
      error:  'alert',
      alert:  'warning' }.with_indifferent_access
  end

  def invite_options_for_select
    User::ROLES.filter_map do |role|
      u = User.new(role: role)
      [u.role_display, role] if policy(u).new?
    end
  end

  def offices_for_select(scope)
    scope.offices.map do |o|
      ["#{o} | #{o.address.state} | Region: #{o.region}", o.id]
    end
  end

  def profile_attributes_required?(user)
    user.volunteer? || user.coordinator?
  end
end

app/views/application/_dropdown_menu.html.haml
- if current_user.admin?
  = link_to admin_root_path do
    .grid-x.menu-item
      .cell.small-9.text-right Admin
      .cell.small-2.small-offset-1
        %i.fas.fa-user-cog
- if current_user.admin? || current_user.coordinator?
  = link_to dashboard_users_path do
    .grid-x.menu-item
      .cell.small-9.text-right Users
      .cell.small-2.small-offset-1
        %i.fas.fa-users
  = link_to dashboard_query_path do
    .grid-x.menu-item
      .cell.small-9.text-right Query
      .cell.small-2.small-offset-1
        %i.fas.fa-users
- if current_user.admin? || current_user.coordinator? || current_user.social_worker?
  = link_to dashboard_reports_path do
    .grid-x.menu-item
      .cell.small-9.text-right Reports
      .cell.small-2.small-offset-1
        %i.fas.fa-file-alt
= link_to edit_user_registration_path do
  .grid-x.menu-item
    .cell.small-9.text-right Profile
    .cell.small-2.small-offset-1
      %i.fas.fa-sliders-h
- if current_user.scheduler?
  = link_to new_need_path, class: 'hide-for-medium' do
    .grid-x.menu-item
      .cell.small-9.text-right New Need
      .cell.small-2.small-offset-1
        %i.fas.fa-plus
  = link_to new_user_invitation_path do
    .grid-x.menu-item
      .cell.small-9.text-right Invite User
      .cell.small-2.small-offset-1
        %i.fas.fa-user-plus
= link_to destroy_user_session_path, method: :delete do
  .grid-x.menu-item
    .cell.small-9.text-right Sign Out
    .cell.small-2.small-offset-1
      %i.fas.fa-sign-out-alt

app/views/application/_nav.html.haml
.nav
  .grid-container
    .grid-x.grid-padding-y
      .cell.shrink
        = link_to root_path do
          = image_pack_tag 'media/images/fosterful.svg', class: 'logo'
      .cell.auto.align-right.align-middle.grid-x
        - if user_signed_in?
          - if policy(Need).new? && !controller_name.in?(%w(registrations verifications))
            = link_to new_need_path, class: 'button success show-for-medium' do
              %fa.fas.fa-plus
              New Need
          %button.show-for-medium.button.dropdown-menu-button{ data: { toggle: 'profile-dropdown' } }
            = current_user.name
            %i.fas.fa-caret-down
          .dropdown-pane.show-for-medium#profile-dropdown{ data: { dropdown: true, position: 'bottom', alignment: 'right' } }
            = render partial: 'dropdown_menu'
          %div{ data: { responsive_toggle: 'mobile-dropdown', hide_for: 'medium' } }
            %button.menu-icon{ data: { toggle: 'mobile-dropdown'} }
        - else
          = link_to 'Sign In', new_user_session_path, class: 'button'
- if user_signed_in?
  .hide-for-medium#mobile-dropdown
    = render partial: 'dropdown_menu'